import { Question } from '../types';

export const ENNEAGRAM_QUESTIONS: Record<'en' | 'es', Question[]> = {
  en: [
    { id: 'q1', text: 'I strive to do things perfectly and get frustrated when they do not meet my high standards.' },
    { id: 'q2', text: 'I focus on the needs of others and like to feel useful and appreciated.' },
    { id: 'q3', text: 'I am very focused on achieving my goals and care a lot about success and recognition.' },
    { id: 'q4', text: 'I feel different from others and seek to express my unique and authentic identity.' },
    { id: 'q5', text: 'I need my private space to think, observe, and understand how the world works.' },
    { id: 'q6', text: 'I tend to anticipate problems, seek security, and am very loyal to my groups or beliefs.' },
    { id: 'q7', text: 'I love experiencing new things, am optimistic, and avoid feeling trapped or bored.' },
    { id: 'q8', text: 'I am direct, assertive, and like to be in control of my life and protect my loved ones.' },
    { id: 'q9', text: 'I prefer to avoid conflicts, seek inner peace, and easily adapt to others.' },
    { id: 'q10', text: 'I find it difficult to relax if I feel my responsibilities are not fully addressed.' },
    { id: 'q11', text: 'I often know what others need before they realize it themselves.' },
    { id: 'q12', text: 'I adapt my image or behavior depending on who I am with to make a good impression.' },
    { id: 'q13', text: 'I usually experience intense emotions and am drawn to emotional depth or melancholy.' },
    { id: 'q14', text: 'I prefer to observe from a distance and gather information before getting actively involved.' },
    { id: 'q15', text: 'I tend to doubt hidden intentions and seek certainty before trusting fully.' },
    { id: 'q16', text: 'I find it hard to focus on a single task because my mind jumps to new ideas or plans.' },
    { id: 'q17', text: 'I am not intimidated by confrontation and often take charge when the situation requires it.' },
    { id: 'q18', text: 'Sometimes I forget my own priorities to go with the flow and maintain harmony.' },
    { id: 'q19', text: 'I make decisions based more on logic and objective analysis than on my feelings.' },
    { id: 'q20', text: 'I consider myself a highly adaptable and resilient person in the face of unexpected changes.' },
  ],
  es: [
    { id: 'q1', text: 'Me esfuerzo por hacer las cosas a la perfección y me frustro cuando no cumplen mis altos estándares.' },
    { id: 'q2', text: 'Me enfoco en las necesidades de los demás y me gusta sentirme útil y apreciado.' },
    { id: 'q3', text: 'Estoy muy enfocado en lograr mis metas y me importa mucho el éxito y el reconocimiento.' },
    { id: 'q4', text: 'Me siento diferente a los demás y busco expresar mi identidad única y auténtica.' },
    { id: 'q5', text: 'Necesito mi espacio privado para pensar, observar y entender cómo funciona el mundo.' },
    { id: 'q6', text: 'Tiendo a anticipar problemas, buscar seguridad y soy muy leal a mis grupos o creencias.' },
    { id: 'q7', text: 'Me encanta experimentar cosas nuevas, soy optimista y evito sentirme atrapado o aburrido.' },
    { id: 'q8', text: 'Soy directo, asertivo y me gusta tener el control de mi vida y proteger a mis seres queridos.' },
    { id: 'q9', text: 'Prefiero evitar conflictos, buscar la paz interior y me adapto fácilmente a los demás.' },
    { id: 'q10', text: 'Me resulta difícil relajarme si siento que mis responsabilidades no están completamente atendidas.' },
    { id: 'q11', text: 'A menudo sé lo que otros necesitan antes de que ellos mismos se den cuenta.' },
    { id: 'q12', text: 'Adapto mi imagen o comportamiento dependiendo de con quién esté para causar una buena impresión.' },
    { id: 'q13', text: 'Usualmente experimento emociones intensas y me atrae la profundidad emocional o la melancolía.' },
    { id: 'q14', text: 'Prefiero observar desde la distancia y recopilar información antes de involucrarme activamente.' },
    { id: 'q15', text: 'Tiendo a dudar de las intenciones ocultas y busco certeza antes de confiar plenamente.' },
    { id: 'q16', text: 'Me cuesta concentrarme en una sola tarea porque mi mente salta a nuevas ideas o planes.' },
    { id: 'q17', text: 'No me intimida la confrontación y a menudo tomo el control cuando la situación lo requiere.' },
    { id: 'q18', text: 'A veces olvido mis propias prioridades para seguir la corriente y mantener la armonía.' },
    { id: 'q19', text: 'Tomo decisiones basadas más en la lógica y el análisis objetivo que en mis sentimientos.' },
    { id: 'q20', text: 'Me considero una persona altamente adaptable y resiliente ante cambios inesperados.' },
  ]
};
